
import os
import sys

# custom modules
sys.path.append('../modules')
from hmac_drbg import DRBG


__version__ = '0.0.2'


if __name__ == '__main__':
    gen = DRBG(b"secret seed")
    data = gen.generate(8)
    print(data)  # b'o\xf7\xc8\x0b\x11+\x9f\x93'

    gen = DRBG(b"Bismuth is a chemical element with symbol Bi and atomic number 83. It is a pentavalent post-transition metal and one of the pnictogens with chemical properties resembling its lighter homologs arsenic and antimony.")
    # Size in Gb - No more than 4Gb from a single seed
    GB = 1
    # CHUNK_SIZE = 65536  # time 3m52.150s
    # CHUNK_SIZE = 1024  # time 3m31.672s
    # Do not change chunk size, it would change the file content.
    CHUNK_SIZE = 1024*4  # time 3m20.990s

    COUNT = GB * 1024 * 1024 * 1024 // CHUNK_SIZE

    with open('rnd.bin', 'wb') as f:
        for chunks in range(COUNT):
            f.write(gen.generate(CHUNK_SIZE))

    print("SHA256")
    os.system("sha256sum rnd.bin")
    print("SHA512")
    os.system("sha512sum rnd.bin")
    print("CRC32")
    os.system("cksfv rnd.bin")

    """
    b'o\xf7\xc8\x0b\x11+\x9f\x93'
    SHA256
    ffe30d8a63e1731e613b16ff8fd040d2946dba6a09823d7cc09d837570c55199  rnd.bin
    SHA512
    5eaffae9fa0b486fa07e4690b3c1f38cfd363eaaf618fb47767b248b4a7650eb4c51a38a88e641e8fce133f18600b5ed229efdcc548eadd9d8a42e3e78a4a4a2  rnd.bin
    CRC32    
    ; Generated by cksfv v1.3.14 on 2018-09-19 at 10:48.20
    ; Project web site: http://www.iki.fi/shd/foss/cksfv/
    ;
    ;   1073741824  10:48.08 2018-09-19 rnd.bin
    rnd.bin 6F30E526

    """
